apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: keycloak
spec:
  connection:
    tLSConfig:
      skipVerify: true  # not cool but refering tlsSecret does not work in release v0.8.13
      #tlsSecret:
      #  name: vault-tls
    address: https://vault.vault.svc.cluster.local:8200
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: vault
  isKVSecretsEngineV2: true
  path: secret/data
  secretKey: password
  secretFormat:
    passwordPolicyName: sylva-password-policy
