---
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: gitea-client
  namespace: keycloak
  labels:
    realm1: sylva
spec:
  realmSelector:
    matchLabels:
      realm1: sylva
  roles:
    - name: admin
    - name: editor
    - name: viewer
  client:
    clientId: gitea
    name: gitea
    enabled: true
    protocol: openid-connect
    publicClient: false
    implicitFlowEnabled: false
    clientAuthenticatorType: client-secret
    rootUrl: "https://${GITEA_DNS}"
    adminUrl: "https://${GITEA_DNS}"
    baseUrl: "https://${GITEA_DNS}"
    redirectUris:
      - "https://${GITEA_DNS}/*"
    webOrigins:
      - "https://${GITEA_DNS}"
    directAccessGrantsEnabled: true
    standardFlowEnabled: true
    attributes:
      use.refresh.tokens: "true"
    defaultClientScopes:
      - "profile"
      - "openid"
      - "email"
      - "roles"
      - "offline_access"
    optionalClientScopes:
      - "phone"
      - "openid"
      - "address"
    protocolMappers:
      - name: Groups Mapper
        protocol: openid-connect
        protocolMapper: oidc-group-membership-mapper
        config:
          full.path: "false"
          id.token.claim: "false"
          access.token.claim: "false"
          userinfo.token.claim: "true"
          claim.name: groups
