# This is a reference for the Realm Manager Operator
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: ExternalKeycloak
metadata:
  name: external-keycloak
  labels:
    realm1: sylva
spec:
  url: https://keycloak-service:8443 # set to the Service created by the new Keycloak Operator
  contextRoot: /
---
#The Admin Credentials need to match those used/created by the new Keycloak Operator
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credential-external-keycloak
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 0s  # `vault-config-operator` can create new versions (>1) of the Vault secret/keycloak value and ESO would by default sync that in Keycloak's credential-external-keycloak secret, but Keycloak app itself would only be using the initial version 1; this stops new version sync
  target:
    creationPolicy: Orphan
    # this Secret is read by the legacy keycloak-realm-operator
    # deployed by this kustomization (name is 'credential-<ExternalKeycloak resource name>')
    name: credential-external-keycloak
    template:
      type: Opaque
      data:
        ADMIN_USERNAME: admin
        ADMIN_PASSWORD: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: secret/data/keycloak
      property: password
 #     version: "1" # setting the version here should not be necessary if ExternalSecret.spec.refreshInterval: 0
