apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/crds/legacy.k8s.keycloak.org_externalkeycloaks_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/crds/legacy.k8s.keycloak.org_keycloakclients_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/crds/legacy.k8s.keycloak.org_keycloakrealms_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/crds/legacy.k8s.keycloak.org_keycloakusers_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/role.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/role_binding.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/service_account.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/1.0.0/deploy/operator.yaml
- external-keycloak.yaml

images:
# Renovate Bot needs additional information to detect the keycloak-realm-operator version:
# renovate: registryUrl=https://quay.io image=keycloak/keycloak-realm-operator
- name: quay.io/keycloak/keycloak-realm-operator
  newName: quay.io/keycloak/keycloak-realm-operator
  newTag: 1.0.0
