apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: sylva-user
  labels:
    realm1: sylva # must match the external-keycloak label
spec:
  realmSelector:
    matchLabels:
      realm1: sylva
  user:
    username: sylva-admin
    enabled: true
    email: sylva-admin@example.com
    emailVerified: true
    firstName: sylva
    lastName: sylva
    groups:
      - infra-admins
    realmRoles:
      - default-roles-sylva
    credentials:
      - type: password
        value: "${SSO_PASSWORD}"
        temporary: false
