apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: sylva
  namespace: keycloak
  labels:
    app: sso
spec:
  keycloakCRName: keycloak
  realm:
    id: sylva
    realm: sylva
    enabled: true
    displayName: Sylva
    loginTheme: keycloak
    accountTheme: keycloak
    adminTheme: keycloak
    passwordPolicy: length(12) and upperCase(1) and lowerCase(1) and digits(1) and forceExpiredPasswordChange(${EXPIRE_PASSWORD_DAYS})
    groups:
    - name: infra-admins
      clientRoles:
        realm-management:
          - view-users
    - name: infra-restricted-admins
    - name: infra-standard-users
    - name: infra-base-users
---
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: sylva
  labels:
    realm1: sylva   # Must match what is declared in external-keycloak.yml
spec:
  unmanaged: true
  realm:
    id: "sylva"
    realm: "sylva"
  instanceSelector:
    matchLabels:
      realm1: sylva
