apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cluster-creator-kubeconfig
spec:
  generateExisting: true
  rules:
  - name: sync-kubeconfig
    match:
      any:
      - resources:
          kinds:
          - kustomize.toolkit.fluxcd.io/v1/Kustomization
          names:
          - cluster
    exclude:
      any:
      - resources:
          namespaces:
          - sylva-system
    generate:
      kind: Secret
      apiVersion: v1
      name: cluster-creator-kubeconfig
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: true
      clone:
        name: cluster-creator-kubeconfig
        namespace: flux-system
