---
apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE}-tls
  # The SERVICE_NAMESPACE must be specified for the kustomizations which
  #   # do not specify a targetNamespace
  namespace: ${CERTIFICATE_NAMESPACE:=default}
type: kubernetes.io/tls
data:
  tls.key: ${KEY}
  tls.crt: ${CERT}
  ca.crt: ${CACERT}
