apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
# Use custom image build with support of rke2 bootstrap provider
- name: gcr.io/k8s-staging-cluster-api/capd-manager:main
  newName: registry.gitlab.com/sylva-projects/sylva-elements/container-images/capd-for-rke2/capd-manager
  newTag: v1.3.4
