apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

configMapGenerator:
  - name: sylva-units-values
    behavior: merge
    files:
      - values=values.yaml
    options:
      disableNameSuffixHash: true
secretGenerator:
  - name: sylva-units-secrets
    behavior: merge
    files:
      - secrets=secrets.yaml
    options:
      disableNameSuffixHash: true
