apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${JOB_TARGET_NAMESPACE}
spec:
  backoffLimit: 5
  activeDeadlineSeconds: ${ACTIVE_DEADLINE_SECONDS:-1800}
  template:
    metadata:
      name: oci-tools-pod
      annotations:
        checksum: s${JOB_CHECKSUM}  # s prefix to avoid this turning into a number if we're unlucky
    spec:
      restartPolicy: Never
      serviceAccountName: ${JOB_NAME}-${JOB_TARGET_NAMESPACE:-sylva-system}-sa
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: oci-tools-container
        image: registry.gitlab.com/sylva-projects/sylva-elements/container-images/oci-tools:0.0.11
        command: ["/bin/sh","-c", "/opt/scripts/push-images-to-glance.py"]
        env:
          - name: OS_CLIENT_CONFIG_FILE
            value: "/etc/openstack/clouds.yaml"
          - name: TARGET_NAMESPACE
            value: ${JOB_TARGET_NAMESPACE}
          - name: ORAS_INSECURE_CLIENT
            value: ${JOB_ORAS_INSECURE_CLIENT}
          - name: http_proxy
            value: ${httpProxy}
          - name: https_proxy
            value: ${httpsProxy}
          - name: no_proxy
            value: ${noProxy}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: openstack-config
          mountPath: /etc/openstack
          readOnly: true
        - name: push-script
          mountPath: /opt/scripts/push-images-to-glance.py
          subPath: push-images-to-glance.py
          readOnly: true
        - name: os-images-info
          mountPath: /opt/config
        - name: tmp-storage
          mountPath: /tmp
      volumes:
      - name: openstack-config
        secret:
          secretName: cluster-cloud-config
      - name: push-script
        configMap:
          name: oci-images-cm
          defaultMode: 0777
          items:
          - key: script.py
            path: push-images-to-glance.py
      - name: os-images-info
        configMap:
          name: os-images-info  # replaced at runtime with a Kustomization patch, by os-images-info-xxxxx
          items:
          - key: values.yaml
            path: os-images-info.yaml
      - name: tmp-storage
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: ${TMP_STORAGE_SIZE:-8Gi}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${JOB_NAME}-${JOB_TARGET_NAMESPACE:-sylva-system}-sa
  namespace: ${JOB_TARGET_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${JOB_NAME}
  namespace: ${JOB_TARGET_NAMESPACE}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${JOB_NAME}
  namespace: ${JOB_TARGET_NAMESPACE}
subjects:
- kind: ServiceAccount
  name: ${JOB_NAME}-${JOB_TARGET_NAMESPACE:-sylva-system}-sa
  namespace: ${JOB_TARGET_NAMESPACE}
roleRef:
  kind: Role
  name: ${JOB_NAME}
  apiGroup: rbac.authorization.k8s.io
