apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
configMapGenerator:
  - name: oci-images-cm
    namespace: ${JOB_TARGET_NAMESPACE}
    behavior: create
    files:
      - script.py=./push-images-to-glance.py
    options:
      disableNameSuffixHash: true
