apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: keycloak
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
spec:
  maxUnavailable: ${MAX_POD_UNAVAILABLE}
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: read
