apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sylva-core
  namespace: sylva-system
spec:
  interval: 5m0s
  type: oci
  url: oci://SYLVA_BASE_OCI_REGISTRY/sylva-core
  # SYLVA_BASE_OCI_REGISTRY is subsituted by $SYLVA_BASE_OCI_REGISTRY by tools/shell-lib/common.sh:define_source
  # this in practice defaults to "oci://registry.gitlab.com/sylva-projects/sylva-core"
