apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/23.0.6/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/23.0.6/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/23.0.6/kubernetes/kubernetes.yml
- keycloak-postgresql-secret.yaml
- keycloak-server.yaml
- keycloak-ingress.yaml
- keycloak-internal-certificate.yaml

patches:
- target:
    kind: Deployment
    name: keycloak-operator
  patch: |
    - op: remove
      path: /spec/selector/matchLabels/app.kubernetes.io~1version
