kind: ConfigMap
apiVersion: v1
metadata:
  name: dummy-deps-${UNIT_NAME}
  namespace: sylva-system
data:
  explanation: |
    This configmap is a dummy resource created by Sylva $UNIT_NAME Kustomization
    to handle dependencies.
