apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: gitea-redis
spec:
  connection:
    tLSConfig:
      skipVerify: true  # not the target, but refering tlsSecret does not work - see https://gitlab.com/sylva-projects/sylva-core/-/issues/261
      #  name: vault-tls
    address: https://vault.vault.svc.cluster.local:8200
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: vault
  isKVSecretsEngineV2: true
  path: secret/data
  secretKey: password
  secretFormat:
    passwordPolicyName: sylva-password-policy
