apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-sylva-ca
  namespace: ${CERTIFICATE_NAMESPACE}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-store-k8s-cert-manager
  target:
    name: sylva-ca.crt
    template:
      type: Opaque
      data:
        ca.crt: |
          {{ .sylvaCa }}
          {{ .extraCaCert }}
  data:
  - secretKey: sylvaCa
    remoteRef:
      key: ca-key-pair
      property: ca.crt
  - secretKey: extraCaCert
    remoteRef:
      key: extra-ca-cert
      property: cacert
