apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineRole
metadata:
  name: sylva-admin
  namespace: vault
spec:
  name: sylva-admin
  connection:
    tLSConfig:
      skipVerify: true # see https://gitlab.com/sylva-projects/sylva-core/-/issues/261
    address: https://vault.vault.svc.cluster.local:8200
  authentication:
    path: kubernetes
    role: admin
  path: oidc
  userClaim: sub
  allowedRedirectURIs:
    - "https://${VAULT_DNS}/v1/auth/oidc/oidc/callback"
    - "https://${VAULT_DNS}/ui/vault/auth/oidc/oidc/callback"
  groupsClaim: group
  tokenPolicies: # SSO user can read the secret path and gains admin privileges
    - secret-reader
    - admin
  tokenTTL: 1h
  boundAudiences:
    - vault
  boundClaims:
    group: infra-admins # must match the keycloak group name set in unit keycloak-resources
  roleType: oidc
