kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ${CLASS_NAME}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  # See https://longhorn.io/docs/1.5.3/references/storage-class-parameters/#longhorn-specific-parameters for documentation of various parameters
  # As all these parameters have to be provided as strings, we encourage the use of postrendering  patches
  # instead of variable substitution to customise these values, otherwise it would interpret numeric values as integer.
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
