apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - xtemplate-cleaner-cronjob.yaml

configMapGenerator:
  - name: cluster-garbage-collector-cm
    namespace: sylva-system
    behavior: create
    files:
      - capi-garbage-cleanup.sh=capi-garbage-cleanup.sh
    options:
      disableNameSuffixHash: true
