---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-garbage-collector-sa
  namespace: sylva-system
  labels:
    app: cluster-garbage-collector
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-garbage-collector
  labels:
    app: cluster-garbage-collector
rules:
  - apiGroups:
      - cluster.x-k8s.io
    verbs:
      - get
      - list
    resources:
      - machinedeployments
      - machinesets
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    verbs:
      - get
      - list
      - delete
    resources:
      - dockermachinetemplates
      - vspheremachinetemplates
      - openstackmachinetemplates
      - metal3machinetemplates
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    verbs:
      - get
      - list
    resources:
      - dockermachines
      - vspheremachines
      - openstackmachines
      - metal3machines
  - apiGroups:
      - controlplane.cluster.x-k8s.io
    verbs:
      - get
      - list
    resources:
      - kubeadmcontrolplanes
      - rke2controlplanes
  - apiGroups:
      - bootstrap.cluster.x-k8s.io
    verbs:
      - get
      - list
      - delete
    resources:
      - kubeadmconfigtemplates
      - rke2configtemplates
  - apiGroups: [""]
    verbs:
      - get
      - list
      - create
    resources:
      - events
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-garbage-collector
  labels:
    app: cluster-garbage-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-garbage-collector
subjects:
  - kind: ServiceAccount
    name: cluster-garbage-collector-sa
    namespace: sylva-system
