---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: gitea-redis
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   refreshInterval: 0s  # `vault-config-operator` can create new versions (>1) of the Vault secret/rancher value and ESO would by default sync that in Rancher's bootstrap secret, but Rancher app itself would only be using the initial version 1; this stops new version sync
   target:
      creationPolicy: Orphan
      name: gitea-redis
      template:
         engineVersion: v2
         data:
            connection_string: 'redis+cluster://:{{ .password }}@gitea-redis-redis-cluster-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&'
            password: '{{ .password }}'
   data:
   - secretKey: password
     remoteRef:
        key: secret/data/gitea-redis
        property: password
