
# External Secret responsible for creating a secret that holds the clientID and clientSecret
# of the Keycloak client that will be used for gitea authentication.
# Secret is then consumed by the 'gitea' unit.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-gitea-oidc
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-store-k8s-keycloak
  target:
    name: gitea-keycloak-oidc-auth # name of the k8s Secret to be created in the same namespace as ExternalSecret
    template:
      engineVersion: v2
      data:
        secret: "{{ .clientSecret }}"
        key: "{{ .clientID }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: keycloak-client-secret-gitea-client # this secret is a byproduct of the gitea-client KeycloakClient resource
        property: CLIENT_SECRET
    - secretKey: clientID
      remoteRef:
        key: keycloak-client-secret-gitea-client
        property: CLIENT_ID
