---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: gitea-admin
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   refreshInterval: 0s  # `vault-config-operator` can create new versions (>1) of the Vault secret/rancher value and ESO would by default sync that in Rancher's bootstrap secret, but Rancher app itself would only be using the initial version 1; this stops new version sync
   target:
      creationPolicy: Orphan
      name: gitea-admin
      template:
         data:
            username: gitea-admin
            password: '{{ .password }}'
   data:
   - secretKey: password
     remoteRef:
        key: secret/data/gitea-admin-user
        property: password
