apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Keycloak
  patch: |
    - op: add
      path: /spec/unsupported/podTemplate/spec/containers/0/env
      value:
        - name: https_proxy
          value: ${https_proxy}
        - name: no_proxy
          value: ${no_proxy}
