apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = "${CLUSTER_ID}"
    insecure-flag = "1"

    [VirtualCenter "${SERVER}"]
    user = "${USERNAME}"
    password = "${PASSWORD}"
    datacenters = "${DATACENTER}"
type: Opaque
