apiVersion: management.cattle.io/v3
builtin: false
description: "Cluster Creator"
displayName: global-cluster-creator
kind: GlobalRole
metadata:
  name: global-cluster-creator
rules:
- apiGroups:
  - provisioning.cattle.io
  resources:
  - clusters
  verbs:
  - create
  - patch
  - list
- apiGroups:
  - management.cattle.io
  resources:
  - clusters
  verbs:
  - get
  - list
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
- nonResourceURLs:
  - "*"
  verbs:
  - get
