apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kube-job
  - role.yaml
  - cluster-creator-global-role.yaml

patches:
  - path: delete-kube-job-cm.yaml

configMapGenerator:
- name: '${JOB_NAME}-${JOB_TARGET_NAMESPACE:-sylva-system}-cm'
  namespace: kube-job
  options:
    disableNameSuffixHash: true
  files:
  - kube-job.sh=cluster-creator-login.sh
