---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${JOB_NAME}-job
  namespace: cattle-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["bootstrap-secret"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${JOB_NAME}-job-binding
  namespace: cattle-system
subjects:
- kind: ServiceAccount
  name: ${JOB_NAME}-${JOB_TARGET_NAMESPACE:-sylva-system}-sa
  namespace: kube-job
roleRef:
  kind: Role
  name: ${JOB_NAME}-job
  apiGroup: rbac.authorization.k8s.io
