apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-harbor-oidc
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-store-k8s-keycloak
  target:
    name: harbor-oidc # name of the k8s Secret to be created in the same namespace as ExternalSecret
    template:
      engineVersion: v2
      data:
        CONFIG_OVERWRITE_JSON: |
          {
            "auth_mode": "oidc_auth",
            "oidc_name": "keycloak",
            "oidc_endpoint": "https://${KEYCLOAK_DNS}/realms/sylva",
            "oidc_groups_claim": "groups",
            "oidc_admin_group": "infra-admins",
            "oidc_client_id": "harbor",
            "oidc_client_secret": "{{ .clientSecret }}",
            "oidc_scope": "openid,email,profile,offline_access",
            "oidc_verify_cert": "true",
            "oidc_auto_onboard": "true",
            "oidc_user_claim": "preferred_username"
          }
  data:
    - secretKey: clientSecret
      remoteRef:
        key: keycloak-client-secret-harbor-client  # this secret is a byproduct of the harbor-client KeycloakClient resource
        property: CLIENT_SECRET
