---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: harbor-init
   namespace: harbor
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   target:
      creationPolicy: Orphan
      name: harbor-init
      template:
         type: Opaque
         data:
            HARBOR_ADMIN_PASSWORD: "{{ .password | toString }}"
   data:
   - secretKey: password
     remoteRef:
        key: secret/data/harbor
        property: password
