apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
- name: falcon-base-secrets
  options:
    disableNameSuffixHash: true
  files:
  - falcon-base-secrets=secrets.yaml

patches:
- target:
    kind: HelmRelease
    name: sylva-units
  patch: |
    - op: add
      path: /spec/valuesFrom/-
      value:
        kind: Secret
        name: falcon-base-secrets
        valuesKey: falcon-base-secrets
