cluster:
  capo:
    ssh_key_name: caas_ci_key
    network_id: 489b1587-4aa4-49b2-be56-62af67efa68f
    rootVolume:
      diskSize: 100
      volumeType: ceph_sas
  machine_deployments:
    md0:
      capo:
        failure_domain: dev-az
openstack:
  storageClass:
    name: cinder-ceph-ssd
    type: ceph_sas

# Add external ceph cluster details
ceph:
  cephfs_csi:
    clusterID: "72451b38-2d3c-11ee-80a2-652991486dfa" # ceph cluster fsid
    fs_name: "test" # ceph fs name
    monitors_ips:
    - 192.168.128.45 # ceph cluster monitors IP

oci_registry_insecure: true

oci_registry_extra_ca_certs: |-
  -----BEGIN CERTIFICATE-----
  MIIFPTCCAyWgAwIBAgIUBCG7warv3pzIgFvBb+wgUZUODDswDQYJKoZIhvcNAQEL
  BQAwHDEaMBgGA1UEAwwRbmV4dXMuc3lsdmEubG9jYWwwHhcNMjMxMDI5MDgwNDAz
  WhcNMzMxMDI2MDgwNDAzWjAcMRowGAYDVQQDDBFuZXh1cy5zeWx2YS5sb2NhbDCC
  AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAODXvIgdyKHmyEpIuxwrT2v2
  FD/5oYvQTMR57ro7Q0EyB7p8MhCMD/WSbtIiwg7xoHH9M8P8sFpo0+Ws9OhXzW9K
  qa83vT7oBVz/0/CLmsfY+iWl3A7297aCaZGP1tmPmDbGiRtmlRZ2mm+mpI4oSgX6
  yEj/LIO7G+8dz/hQUF2ZKVp1ra8teiQ8FOV8yiPUEQPCBBBPD30wkqvw8YUI8Z61
  BNLmhvKz0LgwZKhpdT0dljmIVO3v055mpSK25KJa1DUCiQvmaM2RpODx/CX3t+gN
  PqOgvkxf8bi9L6oMlBzlLxhReZuHUC8gI3sem4jqJ4vjCy64BYgwiRFuLT3g7vPf
  B9rUdyeTs6WXQPoFV0E2Tm3WwyoF+19Q2kWnd5j2YO0WPzaKYP80/5Em3IDLZ+4f
  tqrkn7t+g08+5qpO0hVQBU0JapOwfmr6VWNmXDhEuioSyJrxPtnlApdcyB/9fWNo
  IcbthDN60IPGVC2rlMJznfH06YiZQW6cSDzOGdY4cXi+ndp22UlZnaXfsP1hFaYv
  rN36xMNnfOLzxL2k28OtitLJ4rNuYvQXmsz0we8Ttmb644dZCyNifnnMxfBUggMr
  wMestOLSBAJ3jVu8pUi3DnIiwzM28XA/jjaohh9j6vljzRGqAFk6uJiv9EIrSNZe
  Cj112l48mgrUjmle50AFAgMBAAGjdzB1MB0GA1UdDgQWBBR5FaglSD+bfCbWRw2q
  ASQs+imHBjAfBgNVHSMEGDAWgBR5FaglSD+bfCbWRw2qASQs+imHBjAPBgNVHRMB
  Af8EBTADAQH/MCIGA1UdEQQbMBmCEW5leHVzLnN5bHZhLmxvY2FshwSsFIGOMA0G
  CSqGSIb3DQEBCwUAA4ICAQDKY7pD5YugxAn6kycAPfu844VS/XnCm1k8XZWcis+a
  usHOaH7eD8XSUrpGjPAKbzU2C7YzIQlaoB8UkWxY+ZCU9+DH0SiXPVysaf1O3huU
  G1J6AGdydpWUeu+3141o+ows3EZwTnVRpk/8qEpJra4cDMb6wSZCzygk9hSlVNl9
  7KnBGiTQ/JSiWB146RDri7BEOFikojGtOhb/OIaq8um4vukr7PRT8QrMk5sSUeLj
  NrwZQkWwwiJk+2boS5U3AiJ08IqX3eiFqyowRR3vGpopMzixF96gKMFljLBM0k4a
  mS4hmR+Vm+a/Jpvcnp/e5RhWi8k2dlv4pQP/NbxPsrD/6isONq6lftEl0YLqoyTI
  f1Dvilyq3qBv8klSj45JL67Lt6ivSGTcmMA7v4hPZKimjCGMDuuxMkYrLbc3aorF
  sC9KAXE2mUX60olszTo7Ix+ryNDh+k4tyekr1SoXBHC/sH5K+3zk5/1oZngpE+Rg
  qa/Pblbge6X1XPuma+UHSepzosoivKpRXYn7vd3FRPvhNeEQar2vJcYUjUEOzzgF
  pZU3QdcxsEuQyIKBFM/AoRqu3FAZx/64ZC0qYATG2JZd/57qUYB0n4h683tC+7cm
  r89nQH+Vh95OT1d163A+YOOAkP34aFqKA8vckkH+h7rlRJ55G9HwWDrPE7Up66M8
  YQ==
  -----END CERTIFICATE-----

