apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Mount custom certificat in source controller to workaround https://github.com/fluxcd/flux2/issues/3417
patches:
  - target:
      kind: Deployment
      name: source-controller
    patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: extra-ca-certs
          secret:
            secretName: extra-ca-certs
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: extra-ca-certs
          subPath: extra-ca-certs.pem
          mountPath: /etc/ssl/certs/extra-ca-certs.pem
          readOnly: true

resources:
- certs.yaml
