apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault-pdb
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  maxUnavailable: ${MAX_POD_UNAVAILABLE}
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      vault_cr: vault
