apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: sylva-tests-centos-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: second
            bridge: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      - name: second
        multus:
          networkName: my-bridge
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/centos8-container-disk-images:8.4.2105
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
