apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: WORKLOAD_CLUSTER_NAMESPACE

resources:
- ../../base

patches:
- path: patch-helm-release.yaml
  target:
    kind: HelmRelease
- target:
    kind: Namespace
  patch: |
    kind: _unused_
    metadata:
      name: _unused_
      labels:
        sylva-project.org/shared-workload-cluster-settings: ""

buildMetadata:
- originAnnotations

