---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: cluster-creator-secret
   namespace: flux-system
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   refreshInterval: 0s  # `vault-config-operator` can create new versions (>1) of the Vault secret/rancher value and ESO would by default sync that in Rancher's bootstrap secret, but Rancher app itself would only be using the initial version 1; this stops new version sync
   target:
      creationPolicy: Orphan
      name: cluster-creator-secret
   data:
   - secretKey: password
     remoteRef:
        key: secret/data/cluster-creator-secret
        property: password
