---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: cluster-user-auth
   namespace: flux-system
spec:
   secretStoreRef:
      name: vault
      kind: ClusterSecretStore
   refreshInterval: 0s
   target:
      creationPolicy: Orphan
      name: cluster-user-auth
      template:
         type: kubernetes.io/basic-auth
         data:
            username: ${FLUX_ADMIN_USERNAME}
            password: '{{ htpasswd "" .password | trimPrefix ":" }}'
   data:
   - secretKey: password
     remoteRef:
        key: secret/data/flux-webui
        property: password
